# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VAP-JOBS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VAP-JOBS
	pod 'Alamofire', '4.6.0'
	pod 'SwiftyJSON'
	pod 'SDWebImage', '~> 4.0'
	pod 'FCAlertView'

  target 'VAP-JOBSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
